# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/moto/spyder/extract-files.sh

# All the blobs necessary for spyder

# system/bin
PRODUCT_COPY_FILES += \
vendor/moto/spyder/proprietary/bin/akmd8975:/system/bin/akmd8975 \
vendor/moto/spyder/proprietary/bin/ap_gain.bin:/system/bin/ap_gain.bin \
vendor/moto/spyder/proprietary/bin/ap_gain_mmul.bin:/system/bin/ap_gain_mmul.bin \
vendor/moto/spyder/proprietary/bin/batch:/system/bin/batch \
vendor/moto/spyder/proprietary/bin/btcmd:/system/bin/btcmd \
vendor/moto/spyder/proprietary/bin/bthelp:/system/bin/bthelp \
vendor/moto/spyder/proprietary/bin/bttest_mot:/system/bin/bttest_mot \
vendor/moto/spyder/proprietary/bin/bugtogo.sh:/system/bin/bugtogo.sh \
vendor/moto/spyder/proprietary/bin/charge_only_mode:/system/bin/charge_only_mode \
vendor/moto/spyder/proprietary/bin/chat-ril:/system/bin/chat-ril \
vendor/moto/spyder/proprietary/bin/dbvc_atvc_property_set:/system/bin/dbvc_atvc_property_set \
vendor/moto/spyder/proprietary/bin/dumpe2fs:/system/bin/dumpe2fs \
vendor/moto/spyder/proprietary/bin/dund:/system/bin/dund \
vendor/moto/spyder/proprietary/bin/ecckeyd:/system/bin/ecckeyd \
vendor/moto/spyder/proprietary/bin/enc_mgt_tool:/system/bin/enc_mgt_tool \
vendor/moto/spyder/proprietary/bin/ftmipcd:/system/bin/ftmipcd \
vendor/moto/spyder/proprietary/bin/JuniperVPNTools:/system/bin/JuniperVPNTools \
vendor/moto/spyder/proprietary/bin/libthermal-manager.cfg:/system/bin/libthermal-manager.cfg \
vendor/moto/spyder/proprietary/bin/logcatd:/system/bin/logcatd \
vendor/moto/spyder/proprietary/bin/logcatd-blan:/system/bin/logcatd-blan \
vendor/moto/spyder/proprietary/bin/modemlog:/system/bin/modemlog \
vendor/moto/spyder/proprietary/bin/mot_boot_mode:/system/bin/mot_boot_mode \
vendor/moto/spyder/proprietary/bin/motobox:/system/bin/motobox \
vendor/moto/spyder/proprietary/bin/mount_cdrom.sh:/system/bin/mount_cdrom.sh \
vendor/moto/spyder/proprietary/bin/msp430:/system/bin/msp430 \
vendor/moto/spyder/proprietary/bin/pppd-ril:/system/bin/pppd-ril \
vendor/moto/spyder/proprietary/bin/secclkd:/system/bin/secclkd \
vendor/moto/spyder/proprietary/bin/startup_smc.sh:/system/bin/startup_smc.sh \
vendor/moto/spyder/proprietary/bin/tcmd:/system/bin/tcmd \
vendor/moto/spyder/proprietary/bin/tcmdhelp:/system/bin/tcmdhelp \
vendor/moto/spyder/proprietary/bin/testpppd:/system/bin/testpppd \
vendor/moto/spyder/proprietary/bin/thermaldaemon:/system/bin/thermaldaemon \
vendor/moto/spyder/proprietary/bin/tty2ttyd:/system/bin/tty2ttyd \
vendor/moto/spyder/proprietary/bin/usbd:/system/bin/usbd \
vendor/moto/spyder/proprietary/bin/whisperd:/system/bin/whisperd \
vendor/moto/spyder/proprietary/bin/vpnclientpm:/system/bin/vpnclientpm \

#vendor/moto/spyder/proprietary/bin/wifiupgradecal.sh:/system/bin/wifiupgradecal.sh \
#vendor/moto/spyder/proprietary/bin/wifical.sh:/system/bin/wifical.sh \
#vendor/moto/spyder/proprietary/bin/hostapd:/system/bin/hostapd \
#vendor/moto/spyder/proprietary/bin/crda:/system/bin/crda \
# system/etc
PRODUCT_COPY_FILES += \
vendor/moto/spyder/proprietary/etc/audio_effects.conf:/system/etc/audio_effects.conf \
vendor/moto/spyder/proprietary/etc/backup_targets.csv:/system/etc/backup_targets.csv \
vendor/moto/spyder/proprietary/etc/btpan.conf:/system/etc/btpan.conf \
vendor/moto/spyder/proprietary/etc/ecryptfs.tab:/system/etc/ecryptfs.tab \
vendor/moto/spyder/proprietary/etc/encrypt.tab:/system/etc/encrypt.tab \
vendor/moto/spyder/proprietary/etc/event-log-tags:/system/etc/event-log-tags \
vendor/moto/spyder/proprietary/etc/excluded-input-devices.xml:/system/etc/excluded-input-devices.xml \
vendor/moto/spyder/proprietary/etc/opl.dat.enc:/system/etc/opl.dat.enc \
vendor/moto/spyder/proprietary/etc/priority_notifications_config.xml:/system/etc/priority_notifications_config.xml \
vendor/moto/spyder/proprietary/etc/smc_android_cfg.ini:/system/etc/smc_android_cfg.ini \
vendor/moto/spyder/proprietary/etc/smc_pa.ift:/system/etc/smc_pa.ift \
vendor/moto/spyder/proprietary/etc/smc_pa_pk_4_8Mb_ipa.bin:/system/etc/smc_pa_pk_4_8Mb_ipa.bin \
vendor/moto/spyder/proprietary/etc/smc_pa_pk_4_ipa.bin:/system/etc/smc_pa_pk_4_ipa.bin \
vendor/moto/spyder/proprietary/etc/supportedlocales.conf:/system/etc/supportedlocales.conf \
vendor/moto/spyder/proprietary/etc/mspfirmware/mspfirmware.bin:/system/etc/mspfirmware/mspfirmware.bin \
vendor/moto/spyder/proprietary/etc/mspfirmware/version.txt:/system/etc/mspfirmware/version.txt \
vendor/moto/spyder/proprietary/etc/powervr.ini:/system/etc/powervr.ini \

#vendor/moto/spyder/proprietary/TIInit_10.6.15.bts:/system/etc/firmware/TIInit_10.6.15.bts \

# system/etc/(others)
#vendor/moto/spyder/proprietary/etc/firmware/ducati-m3.bin:/system/etc/firmware/ducati-m3.bin \

PRODUCT_COPY_FILES += \
vendor/moto/spyder/proprietary/etc/firmware/ap_bt_data.bin:/system/etc/firmware/ap_bt_data.bin \
vendor/moto/spyder/proprietary/etc/firmware/ti-connectivity/wl128x-fw-multirole-plt.bin:/system/etc/firmware/ti-connectivity/wl128x-fw-multirole-plt.bin \
vendor/moto/spyder/proprietary/etc/firmware/ti-connectivity/wl128x-fw-multirole-roc.bin:/system/etc/firmware/ti-connectivity/wl128x-fw-multirole-roc.bin \
vendor/moto/spyder/proprietary/etc/firmware/ti-connectivity/wl1271-fw-multirole-plt.bin:/system/etc/firmware/ti-connectivity/wl1271-fw-multirole-plt.bin \
vendor/moto/spyder/proprietary/etc/firmware/ti-connectivity/wl1271-fw-multirole-roc.bin:/system/etc/firmware/ti-connectivity/wl1271-fw-multirole-roc.bin \
vendor/moto/spyder/proprietary/etc/firmware/ti-connectivity/wl1271-nvs.bin:/system/etc/firmware/ti-connectivity/wl1271-nvs.bin \
vendor/moto/spyder/proprietary/etc/nuance/vsuite_config.xml:/system/etc/nuance/vsuite_config.xml \
vendor/moto/spyder/proprietary/etc/ppp/peers/pppd-ril.options:/system/etc/ppp/peers/pppd-ril.options \
vendor/moto/spyder/proprietary/etc/updatecmds/google_generic_update.txt:/system/etc/updatecmds/google_generic_update.txt \
vendor/moto/spyder/proprietary/etc/VideoEditorLite/mve.ini:/system/etc/VideoEditorLite/mve.ini \
vendor/moto/spyder/proprietary/etc/vsensor.d/MeaningFulLocation.vsensor:/system/etc/vsensor.d/MeaningFulLocation.vsensor \
vendor/moto/spyder/proprietary/etc/wifi/wlan_fem.ini:/system/etc/wifi/wlan_fem.ini \
vendor/moto/spyder/proprietary/etc/motorola/12m/key_code_map.txt:system/etc/motorola/12m/key_code_map.txt \
vendor/moto/spyder/proprietary/etc/security/suplcerts.bks:system/etc/security/suplcerts.bks \
vendor/moto/spyder/proprietary/etc/permissions/com.verizon.hardware.telephony.ehrpd.xml:system/etc/permissions/com.verizon.hardware.telephony.ehrpd.xml \
vendor/moto/spyder/proprietary/etc/permissions/com.verizon.hardware.telephony.lte.xml:system/etc/permissions/com.verizon.hardware.telephony.lte.xml \

#vendor/moto/spyder/proprietary/etc/wifi/wpa_supplicant.conf:/system/etc/wifi/wpa_supplicant.conf \
#vendor/moto/spyder/proprietary/etc/wifi/hostapd.conf:/system/etc/wifi/hostapd.conf \

# system/usr
PRODUCT_COPY_FILES += \
vendor/moto/spyder/proprietary/usr/bin/gki_pd_notifier:system/usr/bin/gki_pd_notifier \
vendor/moto/spyder/proprietary/usr/bin/panic_daemon:system/usr/bin/panic_daemon \
vendor/moto/spyder/proprietary/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf \
vendor/moto/spyder/proprietary/usr/share/alsa/cards/aliases.conf:system/usr/share/alsa/cards/aliases.conf \
vendor/moto/spyder/proprietary/usr/share/alsa/pcm/center_lfe.conf:system/usr/share/alsa/pcm/center_lfe.conf \
vendor/moto/spyder/proprietary/usr/share/alsa/pcm/default.conf:system/usr/share/alsa/pcm/default.conf \
vendor/moto/spyder/proprietary/usr/share/alsa/pcm/dmix.conf:system/usr/share/alsa/pcm/dmix.conf \
vendor/moto/spyder/proprietary/usr/share/alsa/pcm/dpl.conf:system/usr/share/alsa/pcm/dpl.conf \
vendor/moto/spyder/proprietary/usr/share/alsa/pcm/dsnoop.conf:system/usr/share/alsa/pcm/dsnoop.conf \
vendor/moto/spyder/proprietary/usr/share/alsa/pcm/front.conf:system/usr/share/alsa/pcm/front.conf \
vendor/moto/spyder/proprietary/usr/share/alsa/pcm/iec958.conf:system/usr/share/alsa/pcm/iec958.conf \
vendor/moto/spyder/proprietary/usr/share/alsa/pcm/modem.conf:system/usr/share/alsa/pcm/modem.conf \
vendor/moto/spyder/proprietary/usr/share/alsa/pcm/rear.conf:system/usr/share/alsa/pcm/rear.conf \
vendor/moto/spyder/proprietary/usr/share/alsa/pcm/side.conf:system/usr/share/alsa/pcm/side.conf \
vendor/moto/spyder/proprietary/usr/share/alsa/pcm/surround40.conf:system/usr/share/alsa/pcm/surround40.conf \
vendor/moto/spyder/proprietary/usr/share/alsa/pcm/surround41.conf:system/usr/share/alsa/pcm/surround41.conf \
vendor/moto/spyder/proprietary/usr/share/alsa/pcm/surround50.conf:system/usr/share/alsa/pcm/surround50.conf \
vendor/moto/spyder/proprietary/usr/share/alsa/pcm/surround51.conf:system/usr/share/alsa/pcm/surround51.conf \
vendor/moto/spyder/proprietary/usr/share/alsa/pcm/surround71.conf:system/usr/share/alsa/pcm/surround71.conf

#vendor/moto/spyder/proprietary/lib/libdevicestats.so:/system/lib/libdevicestats.so \
# system/lib
PRODUCT_COPY_FILES += \
vendor/moto/spyder/proprietary/lib/libadkutils.so:/system/lib/libadkutils.so \
vendor/moto/spyder/proprietary/lib/libamcm.so:/system/lib/libamcm.so \
vendor/moto/spyder/proprietary/lib/libbattd.so:/system/lib/libbattd.so \
vendor/moto/spyder/proprietary/lib/libbcbmsg.so:/system/lib/libbcbmsg.so \
vendor/moto/spyder/proprietary/lib/libbt-aptx-4.0.3.so:/system/lib/libbt-aptx-4.0.3.so \
vendor/moto/spyder/proprietary/lib/libcaps.so:/system/lib/libcaps.so \
vendor/moto/spyder/proprietary/lib/libcapsjava.so:/system/lib/libcapsjava.so \
vendor/moto/spyder/proprietary/lib/libdataencrypt.so:/system/lib/libdataencrypt.so \
vendor/moto/spyder/proprietary/lib/libdataencrypt_tpa.so:/system/lib/libdataencrypt_tpa.so \
vendor/moto/spyder/proprietary/lib/libdataencrypt_utils.so:/system/lib/libdataencrypt_utils.so \
vendor/moto/spyder/proprietary/lib/libdlnahttpjni.so:/system/lib/libdlnahttpjni.so \
vendor/moto/spyder/proprietary/lib/libdlnajni.so:/system/lib/libdlnajni.so \
vendor/moto/spyder/proprietary/lib/libdlnaprofileparser.so:/system/lib/libdlnaprofileparser.so \
vendor/moto/spyder/proprietary/lib/libdlnasysjni.so:/system/lib/libdlnasysjni.so \
vendor/moto/spyder/proprietary/lib/libdmengine.so:/system/lib/libdmengine.so \
vendor/moto/spyder/proprietary/lib/libdmjavaplugin.so:/system/lib/libdmjavaplugin.so \
vendor/moto/spyder/proprietary/lib/libdockcommjni.so:/system/lib/libdockcommjni.so \
vendor/moto/spyder/proprietary/lib/libevbridge.so:/system/lib/libevbridge.so \
vendor/moto/spyder/proprietary/lib/libexempi.so:/system/lib/libexempi.so \
vendor/moto/spyder/proprietary/lib/libextdispjni.so:/system/lib/libextdispjni.so \
vendor/moto/spyder/proprietary/lib/libhdcp.so:/system/lib/libhdcp.so \
vendor/moto/spyder/proprietary/lib/libhdmi.so:/system/lib/libhdmi.so \
vendor/moto/spyder/proprietary/lib/libimage_jni.so:/system/lib/libimage_jni.so \
vendor/moto/spyder/proprietary/lib/libjni_nwp.so:/system/lib/libjni_nwp.so \
vendor/moto/spyder/proprietary/lib/libmetainfo.so:/system/lib/libmetainfo.so \
vendor/moto/spyder/proprietary/lib/libmot_atcmd.so:/system/lib/libmot_atcmd.so \
vendor/moto/spyder/proprietary/lib/libmot_bluetooth_jni.so:/system/lib/libmot_bluetooth_jni.so \
vendor/moto/spyder/proprietary/lib/libmotdrm1.so:/system/lib/libmotdrm1.so \
vendor/moto/spyder/proprietary/lib/libmotdrm1_jni.so:/system/lib/libmotdrm1_jni.so \
vendor/moto/spyder/proprietary/lib/libmotodbgutils.so:/system/lib/libmotodbgutils.so \
vendor/moto/spyder/proprietary/lib/libmoto_mdmctrl.so:/system/lib/libmoto_mdmctrl.so \
vendor/moto/spyder/proprietary/lib/libmoto_netutil.so:/system/lib/libmoto_netutil.so \
vendor/moto/spyder/proprietary/lib/libmss.so:/system/lib/libmss.so \
vendor/moto/spyder/proprietary/lib/libmss.so.sig:/system/lib/libmss.so.sig \
vendor/moto/spyder/proprietary/lib/libnativedrm1.so:/system/lib/libnativedrm1.so \
vendor/moto/spyder/proprietary/lib/libnbgm.so:/system/lib/libnbgm.so \
vendor/moto/spyder/proprietary/lib/libnmea.so:/system/lib/libnmea.so \
vendor/moto/spyder/proprietary/lib/libpanorama.so:/system/lib/libpanorama.so \
vendor/moto/spyder/proprietary/lib/libpanorama_jni.so:/system/lib/libpanorama_jni.so \
vendor/moto/spyder/proprietary/lib/libPhotoEditor.so:/system/lib/libPhotoEditor.so \
vendor/moto/spyder/proprietary/lib/libphotoflow.so:/system/lib/libphotoflow.so \
vendor/moto/spyder/proprietary/lib/libpkip.so:/system/lib/libpkip.so \
vendor/moto/spyder/proprietary/lib/libpppd_plugin-ril.so:/system/lib/libpppd_plugin-ril.so \
vendor/moto/spyder/proprietary/lib/libprovlib.so:/system/lib/libprovlib.so \
vendor/moto/spyder/proprietary/lib/libquicksec.so:/system/lib/libquicksec.so \
vendor/moto/spyder/proprietary/lib/librds_util.so:/system/lib/librds_util.so \
vendor/moto/spyder/proprietary/lib/libril_rds.so:/system/lib/libril_rds.so \
vendor/moto/spyder/proprietary/lib/libscalado.so:/system/lib/libscalado.so \
vendor/moto/spyder/proprietary/lib/libsensorhub_jni.so:/system/lib/libsensorhub_jni.so \
vendor/moto/spyder/proprietary/lib/libsmapi.so:/system/lib/libsmapi.so \
vendor/moto/spyder/proprietary/lib/libtf_crypto_sst.so:/system/lib/libtf_crypto_sst.so \
vendor/moto/spyder/proprietary/lib/libthermal_config.so:/system/lib/libthermal_config.so \
vendor/moto/spyder/proprietary/lib/libthermal_manager.so:/system/lib/libthermal_manager.so \
vendor/moto/spyder/proprietary/lib/libtpa.so:/system/lib/libtpa.so \
vendor/moto/spyder/proprietary/lib/libtpa_core.so:/system/lib/libtpa_core.so \
vendor/moto/spyder/proprietary/lib/libui3d.so:/system/lib/libui3d.so \
vendor/moto/spyder/proprietary/lib/libvideoeditorlite.so:/system/lib/libvideoeditorlite.so \
vendor/moto/spyder/proprietary/lib/libvpnclient_jni.so:/system/lib/libvpnclient_jni.so \
vendor/moto/spyder/proprietary/lib/libvsuite_mot_vs40_cmb.so:/system/lib/libvsuite_mot_vs40_cmb.so \
vendor/moto/spyder/proprietary/lib/libwbxmlparser.so:/system/lib/libwbxmlparser.so \
vendor/moto/spyder/proprietary/lib/libWVphoneAPI.so:/system/libWVphoneAPI.so \
vendor/moto/spyder/proprietary/lib/libXmp_jni.so:/system/lib/libXmp_jni.so \
vendor/moto/spyder/proprietary/lib/libxmpcore.so:/system/lib/libxmpcore.so \
vendor/moto/spyder/proprietary/lib/libWifiAPHardware.so:/system/lib/libWifiAPHardware.so \
vendor/moto/spyder/proprietary/lib/libOMX.ITTIAM.AAC.encode.so:/system/lib/libOMX.ITTIAM.AAC.encode.so \

#vendor/moto/spyder/proprietary/lib/libportaljni.so:/system/lib/libportaljni.so \

# RIL files
PRODUCT_COPY_FILES += \
vendor/moto/spyder/proprietary/bin/base64:/system/bin/base64 \
vendor/moto/spyder/proprietary/bin/extract-embedded-files:/system/bin/extract-embedded-files \
vendor/moto/spyder/proprietary/bin/mm-wrigley-qc-dump.sh:/system/bin/mm-wrigley-qc-dump.sh \
vendor/moto/spyder/proprietary/bin/oem-iptables-init.sh:/system/bin/oem-iptables-init.sh \
vendor/moto/spyder/proprietary/bin/vril-dump:/system/bin/vril-dump \
vendor/moto/spyder/proprietary/bin/wrigley-diag.sh:/system/bin/wrigley-diag.sh \
vendor/moto/spyder/proprietary/bin/wrigley-dump.sh:/system/bin/wrigley-dump.sh \
vendor/moto/spyder/proprietary/bin/wrigley-fetch-mpr.sh:/system/bin/wrigley-fetch-mpr.sh \
vendor/moto/spyder/proprietary/bin/wrigley-iptables.sh:/system/bin/wrigley-iptables.sh \
vendor/moto/spyder/proprietary/lib/libbabysit.so:/system/lib/libbabysit.so \
vendor/moto/spyder/proprietary/lib/libb64.so:/system/lib/libb64.so \
vendor/moto/spyder/proprietary/lib/lib-mot-lte-ril.so:/system/lib/lib-mot-lte-ril.so \
vendor/moto/spyder/proprietary/lib/libmoto_nwif_ril.so:/system/lib/libmoto_nwif_ril.so \
vendor/moto/spyder/proprietary/lib/libmoto_qmi_ril.so:/system/lib/libmoto_qmi_ril.so \
vendor/moto/spyder/proprietary/lib/libmoto_ril.so:/system/lib/libmoto_ril.so \
vendor/moto/spyder/proprietary/lib/libmotdb.so:/system/lib/libmotdb.so \
vendor/moto/spyder/proprietary/lib/moto-ril-multimode.so:/system/lib/moto-ril-multimode.so \

#vendor/moto/spyder/proprietary/lib/libims_client_jni.so:/system/lib/libims_client_jni.so \
# system/lib/hw
PRODUCT_COPY_FILES += \
vendor/moto/spyder/proprietary/lib/hw/gps.spyder.so:/system/lib/hw/gps.spyder.so \
vendor/moto/spyder/proprietary/lib/hw/lights.spyder.so:/system/lib/hw/lights.spyder.so \
vendor/moto/spyder/proprietary/lib/hw/sensors.spyder.so:/system/lib/hw/sensors.spyder.so \
vendor/moto/spyder/proprietary/lib/hw/sensorhub.spyder.so:/system/lib/hw/sensorhub.spyder.so \

# system/xbin
PRODUCT_COPY_FILES += \
vendor/moto/spyder/proprietary/xbin/drm1_func_test:/system/xbin/drm1_func_test \
vendor/moto/spyder/proprietary/xbin/dexdump:/system/xbin/dexdump \
vendor/moto/spyder/proprietary/xbin/nc:/system/xbin/nc \

# system/vendor
PRODUCT_COPY_FILES += \
vendor/moto/spyder/proprietary/vendor/bin/pvrsrvinit:/system/vendor/bin/pvrsrvinit \
vendor/moto/spyder/proprietary/vendor/lib/drm/libdrmwvmplugin.so:/system/vendor/lib/drm/libdrmwvmplugin.so \
vendor/moto/spyder/proprietary/vendor/lib/egl/libeglinfo.so:/system/vendor/lib/egl/libeglinfo.so \
vendor/moto/spyder/proprietary/vendor/lib/egl/libEGL_POWERVR_SGX540_120.so:/system/vendor/lib/egl/libEGL_POWERVR_SGX540_120.so \
vendor/moto/spyder/proprietary/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so:/system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so \
vendor/moto/spyder/proprietary/vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so:/system/vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so \
vendor/moto/spyder/proprietary/vendor/lib/hw/gralloc.omap4.so:/system/vendor/lib/hw/gralloc.omap4.so \
vendor/moto/spyder/proprietary/vendor/lib/libglslcompiler_SGX540_120.so:/system/vendor/lib/libglslcompiler_SGX540_120.so \
vendor/moto/spyder/proprietary/vendor/lib/libIMGegl_SGX540_120.so:/system/vendor/lib/libIMGegl_SGX540_120.so \
vendor/moto/spyder/proprietary/vendor/lib/libpvr2d_SGX540_120.so:/system/vendor/lib/libpvr2d_SGX540_120.so \
vendor/moto/spyder/proprietary/vendor/lib/libpvrANDROID_WSEGL_SGX540_120.so:/system/vendor/lib/libpvrANDROID_WSEGL_SGX540_120.so \
vendor/moto/spyder/proprietary/vendor/lib/libPVRScopeServices.so:/system/vendor/lib/libPVRScopeServices.so \
vendor/moto/spyder/proprietary/vendor/lib/libsrv_init_SGX540_120.so:/system/vendor/lib/libsrv_init_SGX540_120.so \
vendor/moto/spyder/proprietary/vendor/lib/libsrv_um_SGX540_120.so:/system/vendor/lib/libsrv_um_SGX540_120.so \
vendor/moto/spyder/proprietary/vendor/lib/libusc_SGX540_120.so:/system/vendor/lib/libusc_SGX540_120.so \
vendor/moto/spyder/proprietary/vendor/lib/libwvdrm_L3.so:/system/vendor/lib/libwvdrm_L3.so \
vendor/moto/spyder/proprietary/vendor/lib/libwvm.so:/system/vendor/lib/libwvm.so \
vendor/moto/spyder/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:/system/vendor/lib/libWVStreamControlAPI_L3.so \

# Camera libs we need for now
PRODUCT_COPY_FILES += \
vendor/moto/spyder/proprietary/lib/libpostcapimgproc_intf.so:/system/lib/libpostcapimgproc_intf.so \
vendor/moto/spyder/proprietary/lib/hw/camera.omap4.so:/system/lib/hw/camera.omap4.so \

# All the apks necessary for spyder
PRODUCT_PACKAGES += \
	AppDirectedSmsService \
	MotoImsServer \
	MotoLocationProxy \
	MotoLteTelephony \
	MotoModemUtil \
	MotoSimUiHelperICS \
	vzwapnpermission
